<?php

namespace Tests\Dojo;

use Webmozart\Assert\InvalidArgumentException;
use App\Movie;
use PHPUnit\Framework\TestCase;
use Faker;

class MovieTest extends TestCase
{
    public array $data;
    public Faker\Generator $faker;

    protected function setUp(): void
    {
        $this->faker = Faker\Factory::create();
        $faker = $this->faker;
        $this->data = [];
        $this->data["id"] = 1;
        $this->data["title"] = $faker->text(100);
        $this->data["overview"] = $faker->realTextBetween(160, 500);
        $this->data["release_date"] = $faker->date();
        $this->data["rating"] = $faker->randomFloat(2, 0, 5);
        $this->data["poster"] = $faker->sha1() . ".jpg";
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testShouldFailWhenTitleIsEmpty(): void {
        $this->data["title"] = "";
        $this->expectException(InvalidArgumentException::class);
        $movie = Movie::fromArray($this->data);
    }

    public function testShouldFailWhenTitleIsTooLong(): void {
        $this->data["title"] = $this->faker->realTextBetween(101,200);
        $this->expectException(InvalidArgumentException::class);
        $movie = Movie::fromArray($this->data);
    }

    public function testShouldPassWhenDataIsCorrect(): void {
        $movie = Movie::fromArray($this->data);
        $this->assertInstanceOf(Movie::class, $movie);
    }

}